# Setup
title:               Konstantin Nomerotski
tagline:             ""
description:         'Chemistry, Software, and other stuff'
url:                 /lanyon
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Konstantin Nomerotski
  url:               url
  email:             kon50@hotmail.co.uk

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
